name: Python Tests

on:
  pull_request:
    branches:
      - main  # Change this to your default branch if it's not main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.12'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure you have this file with your dependencies

      - name: Run tests
        run: |
          pytest --cov --pylint  # Replace with your package name
        continue-on-error: false

      - name: Check code coverage
        run: |
          coverage report --fail-under=100  # This will fail the job if coverage is less than 100
        continue-on-error: false

  check:
    runs-on: ubuntu-latest
    needs: tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check test results
        run: |
          if [ -f ".pytest_cache" ]; then
            echo "Tests failed or coverage not 100% or pylint did not pass"
            exit 1
          fi
